apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deployment
  namespace: movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie
  template:
    metadata: 
      labels:
        app: movie
    spec:
      containers: 
      - name: movie-container 
        image: movie-image:latest
        ports:
        - containerPort: 8080
        env:
        - name: REACT_APP_TMDB_API_KEY
          value: "your_tmdb_api_key_here"

